### API CLIENTE - GET
GET http://localhost:8080/api/v1/Servicos


### API CLIENTE - POST
POST http://localhost:8080/api/v1/Servicos
Content-Type: application/json

{
    
    "descricao": "Lavação à seco",
    "preco":"0.0"
    
    
    
    
    

}


### API CLIENTE - PUT
PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json


{
    "nome": "zezinho da silva",
    "telefone": "55555",
    "codigo": "1"
    
}


### API CLIENTE - DELETE
DELETE http://localhost:8080/api/v1/clientes/1
Content-Type: application/json