### API CLIENTE - GET
GET http://localhost:8080/api/v1/clientes


### API CLIENTE - POST
POST http://localhost:8080/api/v1/clientes
Content-Type: application/json

{
    "nome": "zezinho",
    "telefone": "55512345",
    "codigo": "1",
    "roupas": [
        {}
    ],
    
    
    

}


### API CLIENTE - PUT
PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json


{
    "nome": "zezinho da silva",
    "telefone": "55555",
    "codigo": "1"
    
}


### API CLIENTE - DELETE
DELETE http://localhost:8080/api/v1/clientes/1
Content-Type: application/json